#!/bin/bash

set -e

if [[ -n "${ZS_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [command]
Run a Lapis command line tool.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker-compose run --rm \
            lapis "$@"
    fi
fi
