#!/bin/bash

set -e

if [[ -n "${ZS_DEBUG}" ]]; then
  set -x
fi

function usage() {
  echo -n "Usage: $(basename "$0") [--stop]
Start or stop SRCDS.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  if [[ "${1:-}" == "--help" ]]; then
    usage
  elif [[ "${1:-}" == "--stop" ]]; then
    docker-compose stop
  else
    docker-compose up -d
  fi
fi
