#!/bin/bash

if [[ -n "${ZS_DEBUG}" ]]; then
  set -x
fi

function usage() {
  echo -n \
    "Usage: $(basename "$0")
Build container images and update dependencies.
"
}

function fastdl() {
  input_dir="${1}"
  output_dir="${2}"
  resource_file="${3}"

  declare -a prefixes
  prefixes=(maps materials models particles resource sound)

  # Wipe existing resource file
  if [[ $resource_file ]]; then
    mkdir -p "${resource_file%/*}"
    >"${resource_file}"
  fi

  for prefix in "${prefixes[@]}"; do
    find "${input_dir}" -maxdepth 1 -type d -name "${prefix}" | while read dir; do
      find "${dir}" -type f ! -name "*.bz2" -a ! -name ".DS_Store" | while read file; do
        # Subtractr the input dir to get the virtual path of the file
        # for FastDL
        resource=${file#${input_dir}/}

        # Append new resource.AddFile statement
        if [[ $resource_file ]] && [[ ! $resource =~ ^maps/[[:alnum:]]+ ]]; then
          printf "resource.AddFile(\"%s\")\n" "${resource}" >>"${resource_file}"
        fi

        # Ensure FastDL directory structure exists
        mkdir -p "${output_dir}/${resource%/*}"

        # Only recompress resources if SHA512/256 is invalid
        compressed_resource="${output_dir}/${resource}.bz2"
        if [[ ! $(shasum -a 512256 -c "${compressed_resource}.sha512256") ]]; then
          echo "Processing ${resource}"

          bzip2 -k -c "${file}" >"${compressed_resource}"
          shasum -a 512256 "${compressed_resource}" >"${compressed_resource}.sha512256"

          # Hack to make SRCDS recognize bz2 files exist on FastDL
          if [[ $resource =~ ^maps/[[:alnum:]]+ ]]; then
            cp "${file}" "${output_dir}/${resource}"
          fi
        fi
      done
    done
  done
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  if [[ "${1:-}" == "--help" ]]; then
    usage
  else
    # Make sure container images are up-to-date
    docker-compose build --pull

    # Pull map files from from S3
    docker-compose run --rm --no-deps awscli \
      ./scripts/sync-maps

    # Compress gamemode content
    fastdl \
      ./src/garrysmod/gamemodes/zombiesurvival/content \
      ./build/fastdl \
      ./src/garrysmod/gamemodes/zombiesurvival/gamemode/sv_resources.lua

    # Push FastDL artifacts to S3
    docker-compose run --rm --no-deps awscli \
      ./scripts/sync-fastdl

    # Bring up PostgreSQL and Lapis in a way that respects
    # configured service health checks.
    docker-compose \
      -f docker-compose.yml \
      up -d database lapis

    # Apply any outstanding Lapis migrations
    ./scripts/manage migrate
  fi
fi
